# Generated by Django 2.1.5 on 2019-12-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max: 100 chars.', max_length=100, verbose_name='Project title.')),
                ('prev_description', models.TextField(help_text='Max: 300chars.', max_length=300, verbose_name='Short description.')),
                ('description', models.TextField(help_text='Max: 2500 chars.', max_length=2500, verbose_name='Description.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(blank=True, choices=[('p', 'Planning'), ('i', 'Implementation'), ('m', 'Maintenance'), ('c', 'Completion')], default='p', help_text='Project phase.', max_length=1)),
            ],
        ),
    ]
