# Generated by Django 2.1.5 on 2020-02-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Path: projects/static/img/projects/', null=True, upload_to='projects/static/img/projects/')),
                ('description', models.CharField(max_length=1000, verbose_name='Image description')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max: 100 chars.', max_length=100, verbose_name='Project title.')),
                ('prev_description', models.TextField(help_text='Max: 200 chars.', max_length=200, verbose_name='Short description.')),
                ('description', models.TextField(help_text='Max: 100000 chars. Use HTML to make it look good.', max_length=100000, verbose_name='Description.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(blank=True, choices=[('p', 'Planning'), ('i', 'Implementation'), ('m', 'Maintenance'), ('c', 'Completion')], default='p', help_text='Project phase.', max_length=1)),
                ('sm_img', models.ImageField(help_text='572x360px', null=True, upload_to='projects/static/img/projects/', verbose_name='Small image (thumbnail for mobile devices)')),
                ('md_img', models.ImageField(help_text='1149x370px', null=True, upload_to='projects/static/img/projects/', verbose_name='Medium image (thumbnail for screens)')),
                ('lg_img', models.ImageField(help_text='1680x1050px', null=True, upload_to='projects/static/img/projects/', verbose_name='Large image (background for the project detail page)')),
                ('public', models.BooleanField(default=False)),
                ('img', models.ManyToManyField(to='projects.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Project tag')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(to='projects.Tag'),
        ),
    ]
