# Generated by Django 2.1.5 on 2020-02-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='public',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('t', 'Test'), ('e', 'Edit'), ('p', 'public')], default='e', help_text='Status of the post.', max_length=1),
        ),
    ]
