# Generated by Django 2.1.5 on 2020-02-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200216_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Image description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ManyToManyField(blank=True, to='projects.Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lg_img',
            field=models.ImageField(blank=True, help_text='1680x1050px', null=True, upload_to='projects/static/img/projects/', verbose_name='Large image (background for the project detail page)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='md_img',
            field=models.ImageField(blank=True, help_text='1149x370px', null=True, upload_to='projects/static/img/projects/', verbose_name='Medium image (thumbnail for screens)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sm_img',
            field=models.ImageField(blank=True, help_text='572x360px', null=True, upload_to='projects/static/img/projects/', verbose_name='Small image (thumbnail for mobile devices)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(blank=True, to='projects.Tag'),
        ),
    ]
