# Generated by Django 2.1.5 on 2020-01-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200128_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Max: 10000 chars.', max_length=10000, verbose_name='Description.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='prev_description',
            field=models.TextField(help_text='Max: 200 chars.', max_length=200, verbose_name='Short description.'),
        ),
    ]
