# Generated by Django 2.1.5 on 2020-01-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200128_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lg_img',
            field=models.ImageField(help_text='1680x1050px', null=True, upload_to='projects_img/', verbose_name='Large image (background for the project detail page)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='md_img',
            field=models.ImageField(help_text='1149x370px', null=True, upload_to='projects_img/', verbose_name='Medium image (thumbnail for screens)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sm_img',
            field=models.ImageField(help_text='572x360px', null=True, upload_to='projects_img/', verbose_name='Small image (thumbnail for mobile devices)'),
        ),
    ]
