# Generated by Django 2.1.5 on 2020-02-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200210_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(to='projects.Tag'),
        ),
    ]
