# Generated by Django 2.1.5 on 2020-02-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200211_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
