# Generated by Django 2.1.5 on 2020-02-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200211_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Path: projects/static/img/projects/', null=True, upload_to='projects/static/img/projects/')),
                ('description', models.CharField(max_length=1000, verbose_name='Image description')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Max: 100000 chars. Use HTML to make it look good.', max_length=100000, verbose_name='Description.'),
        ),
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ManyToManyField(null=True, to='projects.Image'),
        ),
    ]
