# Generated by Django 2.1.5 on 2020-02-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200211_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ManyToManyField(to='projects.Image'),
        ),
    ]
