# Generated by Django 2.1.5 on 2020-02-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200211_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(blank=True, choices=[('p', 'Planning'), ('s', 'Design'), ('v', 'Development'), ('m', 'Maintenance'), ('c', 'Completion')], default='p', help_text='Project phase.', max_length=1),
        ),
    ]
