# Generated by Django 2.1.5 on 2020-02-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200215_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(blank=True, choices=[('p', 'Planning'), ('i', 'Implementation'), ('m', 'Maintenance'), ('c', 'Completion')], default='p', help_text='Project phase.', max_length=1),
        ),
    ]
